### ISSUE TITLE
Host app icons in individual app repo github.io pages

### ISSUE THREAD

**Issue by KevinGrandon** [fxos/directory#1]
It seems like it might be a better idea to host the icons externally, and point to the URLs inside of the list model? What do you think @mikehenrty ?

**Comment by mikehenrty** [comment]
Where were you thinking we host the icons? Github pages for directory, or the apps repos themselves? If the former, we should probably just host this entire app on github?

**Comment by KevinGrandon** [comment]
I think they should be hosted wherever we host the apps themselves. Did we decide that yet? I think we were still debating between heroku or gh-pages.

**Comment by mikehenrty** [comment]
What does hosting them externally buy us?

**Comment by mikehenrty** [comment]
This issue is actually fixed now. We host the icons in the individual app repos now.
